app.mode=mock
app.refresh.seconds=30
app.warning.threshold.minutes=30
app.data.rules.path=src/main/resources/data/monitoring-rules.json
app.data.alerts.path=src/main/resources/data/alert-history.json
app.data.acks.path=src/main/resources/data/acknowledgements.json
app.mock.process.instance.path=src/main/resources/mockdb/process_instance.json
app.mock.process.attribute.path=src/main/resources/mockdb/process_attribute.json
app.mock.process.template.path=src/main/resources/mockdb/process_template.json
db2.jndi.name=jdbc/bevakningDb
